[project]
name = "PyMoss"
version = "0.1.0"

description = "Python bindings for the Moss Framework using pybind11"

readme = "README.md"

requires-python = ">=3.10"

license = "MIT"

authors = [ { name = "TxbiG" } ]

keywords = [
    "moss",
    "moss-framework",
    "game-development",
    "game-engine",
    "pybind11",
    "python",
    "graphics",
    "physics",
    "audio"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Programming Language :: C++ :: C++17",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: MacOS"
]

[project.urls]
Homepage = "https://github.com/TxbiG/PyMoss"
Repository = "https://github.com/TxbiG/PyMoss"
Documentation = "https://github.com/TxbiG/PyMoss/tree/main/docs"
Issues = "https://github.com/TxbiG/PyMoss/issues"
Changelog = "https://github.com/TxbiG/PyMoss/blob/main/CHANGELOG.md"
